def express_love_and_cuteness():
    # Message of love
    print("I love you, Keyla! Here are 100 cute things about you:")

    # List of 100 cute things
    cute_things = [
        "Your radiant smile",
        "The sparkle in your eyes",
        "The way you laugh",
        "Your kind heart",
        "Your brilliant mind",
        "The way you make everyone feel special",
        "Your quirky sense of humor",
        "How you always know what to say",
        "Your passion for life",
        "The way you inspire me every day",
        "Your adorable dimples",
        "How you care for animals",
        "Your amazing cooking skills",
        "The way you dance when you're happy",
        "Your love for adventure",
        "How you always see the best in people",
        "Your gorgeous hair",
        "The way you sing in the car",
        "Your thoughtful surprises",
        "Your artistic talent",
        "The way you light up a room",
        "Your endless curiosity",
        "Your courage to stand up for what's right",
        "The way you listen so attentively",
        "Your soft, warm hugs",
        "Your love for books",
        "The way you make me laugh",
        "Your impeccable sense of style",
        "Your patience and understanding",
        "Your beautiful soul",
        "Your sense of adventure",
        "The way you support my dreams",
        "Your incredible work ethic",
        "Your infectious enthusiasm",
        "The way you make me feel loved",
        "Your sweet voice",
        "Your endless creativity",
        "Your compassion for others",
        "Your resilience in tough times",
        "Your unique perspective on life",
        "Your playful nature",
        "The way you remember the little things",
        "Your genuine kindness",
        "Your ability to stay positive",
        "Your beautiful handwriting",
        "The way you cheer me up",
        "Your love for sunsets",
        "Your sparkling personality",
        "Your dedication to your goals",
        "Your love for music",
        "The way you take care of others",
        "Your ability to make anyone feel special",
        "Your wonderful sense of humor",
        "The way you tackle challenges",
        "Your passion for learning",
        "Your radiant positivity",
        "Your appreciation for the small things",
        "Your ability to stay calm",
        "Your love for nature",
        "Your beautiful laugh",
        "The way you bring out the best in me",
        "Your endless generosity",
        "Your sweet texts",
        "Your incredible memory",
        "Your infectious energy",
        "Your strong sense of loyalty",
        "Your love for family",
        "The way you tell stories",
        "Your cute nicknames for me",
        "Your love for trying new things",
        "Your open-mindedness",
        "Your ability to make friends easily",
        "Your adventurous spirit",
        "The way you look at me",
        "Your love for art",
        "Your sweet surprises",
        "Your beautiful heart",
        "Your wonderful taste in movies",
        "Your gentle spirit",
        "Your thoughtfulness",
        "The way you make everyday moments special",
        "Your love for coffee (or tea, if applicable!)",
        "Your amazing photography skills",
        "Your strong and independent nature",
        "Your playful jokes",
        "Your love for travel",
        "Your love for life",
        "The way you blush when you're shy",
        "Your love for celebrations",
        "Your graceful way of handling situations",
        "Your beautiful dreams",
        "The way you keep me grounded",
        "Your love for learning new things",
        "Your never-give-up attitude",
        "The way you believe in me",
        "Your warmth and tenderness",
        "The way you make me a better person",
        "Your unshakable confidence",
        "Your endless love and support"
    ]

    # Printing each cute thing
    for i, thing in enumerate(cute_things, 1):
        print(f"{i}. {thing}")

# Call the function
express_love_and_cuteness()
